"""Generate edge-case topologies in data/generated by default."""

import argparse
from pathlib import Path

DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parents[1] / "data" / "generated"


def generate_infinite_loop(output_dir=DEFAULT_OUTPUT_DIR):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    print("Generating Infinite Loop Topology...")
    with (output_dir / "rel_loop.txt").open("w") as output:
        # AS 1 -> AS 2 -> AS 3 -> AS 1 (circular dependency).
        output.write("1|2|-1\n2|3|-1\n3|1|-1\n")
    with (output_dir / "ann_loop.txt").open("w") as output:
        output.write("asn,prefix,rov\n")
        output.write("1,192.168.1.0/24,0\n")


def generate_island_clusters(output_dir=DEFAULT_OUTPUT_DIR):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    print("Generating Disconnected Island Topology...")
    with (output_dir / "rel_island.txt").open("w") as output:
        output.write("1|2|-1\n")  # Cluster A
        output.write("3|4|-1\n")  # Cluster B
    with (output_dir / "ann_island.txt").open("w") as output:
        output.write("asn,prefix,rov\n")
        output.write("1,10.0.0.0/8,0\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR,
                        help="destination directory (default: repository data/generated)")
    args = parser.parse_args()
    generate_infinite_loop(args.output_dir)
    generate_island_clusters(args.output_dir)
    print(f"Edge-case topologies generated in {args.output_dir}.")
