"""Generate a large synthetic dataset in data/generated by default."""

import argparse
import random
from pathlib import Path

NUM_ASES = 15_000
NUM_LINKS = 45_000
NUM_ANNOUNCEMENTS = 30_000
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parents[1] / "data" / "generated"


def generate_data(output_dir=DEFAULT_OUTPUT_DIR):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"Generating {output_dir / 'rel.txt'}...")
    with (output_dir / "rel.txt").open("w") as output:
        for _ in range(NUM_LINKS):
            u = random.randint(1, NUM_ASES)
            v = random.randint(1, NUM_ASES)
            if u == v:
                continue
            # Enforce strict hierarchy: smaller AS is always the provider.
            if u > v:
                u, v = v, u
            # -1 (u is provider to v) or 0 (peer-to-peer).
            rel = random.choice([-1, 0])
            output.write(f"{u}|{v}|{rel}\n")

    print(f"Generating {output_dir / 'ann.txt'}...")
    with (output_dir / "ann.txt").open("w") as output:
        output.write("asn,prefix,rov\n")
        for _ in range(NUM_ANNOUNCEMENTS):
            asn = random.randint(1, NUM_ASES)
            prefix = f"{random.randint(1, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}.0/24"
            output.write(f"{asn},{prefix},0\n")
    print("Done! Generated a large acyclic synthetic BGP dataset.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR,
                        help="destination directory (default: repository data/generated)")
    args = parser.parse_args()
    generate_data(args.output_dir)
